<x-layouts.app>
    @include('sections.hero')
    @include('sections.services')
    @include('sections.about')
    @include('sections.benefits')
    @include('sections.testimonials')
    @include('sections.location')
    @include('sections.contact')
</x-layouts.app>
