<?php

return [
    'indexable' => env('SITE_INDEXABLE', false),
    'canonical_redirects' => env('SITE_CANONICAL_REDIRECTS', false),
    'alternate_hosts' => ['danksandstrydom.co.za', 'www.danksandstrydom.co.za'],
    'analytics_enabled' => env('SITE_ANALYTICS_ENABLED', false),
    'pages' => [
        'about' => ['path' => '/about', 'published' => true, 'title' => 'About Danks & Strydom', 'description' => 'Contact Danks & Strydom Physiotherapy in Glen Marais, Kempton Park to discuss your enquiry and practitioner availability.', 'heading' => 'About Danks & Strydom', 'intro' => 'Danks & Strydom is a physiotherapy practice in Glen Marais, Kempton Park.', 'sections' => ['Speak to the practice' => 'Contact the practice to ask which physiotherapist can help with your enquiry. You can also ask about their qualifications and experience relevant to your needs.']],
        'contact' => ['path' => '/contact', 'published' => true, 'title' => 'Contact & Directions', 'description' => 'Contact Danks & Strydom Physiotherapy in Glen Marais, Kempton Park. Request an appointment and confirm directions before your visit.', 'heading' => 'Contact and directions', 'intro' => 'Request an appointment or ask the practice a question. An enquiry does not confirm an appointment.', 'sections' => []],
        'services' => ['path' => '/services', 'published' => true, 'title' => 'Physiotherapy Enquiries in Kempton Park', 'description' => 'Discuss your physiotherapy needs with Danks & Strydom in Glen Marais, Kempton Park and ask about available assessment and rehabilitation.', 'heading' => 'Discuss your physiotherapy needs', 'intro' => 'Tell the practice what you are seeking help with so you can discuss the appropriate next step.', 'sections' => ['Choosing an appointment' => 'Ask about the type of appointment available, the practitioner you would see and any information needed beforehand. You do not need to choose a treatment from a list to send an enquiry.']],
        // Publish individually in a reviewed code change after clinical approval.
        'back-neck-pain' => ['path' => '/services/back-neck-pain', 'published' => false, 'title' => 'Back & Neck Pain Physio in Kempton Park', 'description' => 'Ask Danks & Strydom in Glen Marais about physiotherapy for back and neck pain and arranging an assessment.', 'heading' => 'Back and neck pain', 'intro' => 'Looking for help with back or neck pain in Kempton Park? Contact the practice to discuss an assessment.', 'sections' => ['Is this the right appointment?' => 'Ask whether the practice can assess your back or neck concern and which physiotherapist would see you.', 'Discussing an assessment' => 'Ask what an assessment involves and how to explain the activities that are difficult for you.', 'Planning any follow-up' => 'Ask how the physiotherapist would discuss next steps with you and when another assessment or referral may be needed.', 'Before arranging a visit' => 'Confirm what information to bring and whether any referral documents are needed.']],
        'sports-injury-rehabilitation' => ['path' => '/services/sports-injury-rehabilitation', 'published' => false, 'title' => 'Sports Physio in Kempton Park', 'description' => 'Ask Danks & Strydom in Glen Marais about sports injury rehabilitation and arranging a physiotherapy appointment.', 'heading' => 'Sports injury rehabilitation', 'intro' => 'Contact the practice about your sport, activity and rehabilitation enquiry.', 'sections' => ['Your sport and activity' => 'Ask whether the practice works with your type of injury, sport and activity, and which practitioner would be appropriate.', 'Your assessment enquiry' => 'Ask about assessment for a recent injury or an ongoing rehabilitation need.', 'Returning to activity' => 'Discuss your goals and any guidance you have already received. Ask how decisions about progression are made; an enquiry does not establish a return-to-sport date.', 'Arranging follow-up' => 'Ask what information is needed beforehand and how follow-up appointments are arranged.']],
        'post-operative-rehabilitation' => ['path' => '/services/post-operative-rehabilitation', 'published' => false, 'title' => 'Post-Operative Physio in Kempton Park', 'description' => 'Enquire about physiotherapy after surgery at Danks & Strydom in Glen Marais, Kempton Park.', 'heading' => 'Rehabilitation after surgery', 'intro' => 'Ask the practice about rehabilitation after your procedure before arranging an appointment.', 'sections' => ['Confirm the scope of care' => 'Ask whether the practice supports rehabilitation following your procedure and which clinician would be involved.', 'Before the first appointment' => 'Ask which surgeon instructions and referral documents are needed, and how to discuss timing and any restrictions before attending.', 'Discussing rehabilitation' => 'Ask how assessment, goals and follow-up would be discussed with you and your referring clinician where appropriate.', 'Appointment arrangements' => 'Contact the practice to confirm availability and the information needed to arrange a visit. No recovery timeline is established by this page.']],
        'patient-information' => ['path' => '/patient-information', 'published' => false, 'title' => 'Patient Information', 'description' => 'Questions to discuss with Danks & Strydom before your physiotherapy appointment in Glen Marais.', 'heading' => 'Before your first appointment', 'intro' => 'Contact the practice to confirm the arrangements for your visit.', 'sections' => ['Requesting an appointment' => 'Ask about availability and how an appointment is confirmed. Sending the enquiry form alone does not confirm a booking.', 'Fees and medical aid' => 'Ask the practice about fees, payment and medical-aid arrangements before attending.', 'Referrals and preparation' => 'Ask whether referral documents are needed, what to bring and what to expect at a first appointment.', 'Changing an appointment' => 'Contact the practice to ask how changes or cancellations should be arranged.', 'Getting to the practice' => 'Confirm the address and entrance before travelling. Ask about any access requirements you would like to discuss.']],
    ],
];
