<?php

return [
    'indexable' => env('SITE_INDEXABLE', false),
    'canonical_redirects' => env('SITE_CANONICAL_REDIRECTS', false),
    'alternate_hosts' => ['danksandstrydom.co.za', 'www.danksandstrydom.co.za'],
    'analytics_enabled' => env('SITE_ANALYTICS_ENABLED', false),
    'review_preview' => env('SITE_REVIEW_PREVIEW', false),
    'review_username' => env('SITE_REVIEW_USERNAME', ''),
    'review_password_hash' => env('SITE_REVIEW_PASSWORD_HASH', ''),
    'pages' => [
        'about' => [
            'path' => '/about',
            'published' => false,
            'title' => 'About Danks & Strydom',
            'description' => 'Meet Elize Strydom and Cheryl Myburgh at Danks & Strydom Physiotherapy in Glen Marais, Kempton Park.',
            'heading' => 'About Danks & Strydom',
            'intro' => 'Danks & Strydom is a physiotherapy practice in Glen Marais, Kempton Park. Elize Strydom and Cheryl Myburgh both hold degrees in physiotherapy.',
            'sections' => [
                'Our services' => 'Both physiotherapists provide back and neck pain physiotherapy, sports injury rehabilitation and post-operative rehabilitation.',
            ],
            'practitioners' => [
                [
                    'name' => 'Cheryl Myburgh',
                    'title' => 'Physiotherapist',
                    'biography' => 'Cheryl Myburgh has extensive experience in human and equine physiotherapy. At Danks & Strydom, she provides physiotherapy care for patients attending the practice.',
                ],
                [
                    'name' => 'Elize Strydom',
                    'title' => 'Physiotherapist',
                    'biography' => 'Elize Strydom practises human physiotherapy at Danks & Strydom, assessing patients and providing treatment based on their individual needs.',
                ],
            ],
        ],
        'contact' => [
            'path' => '/contact',
            'published' => true,
            'title' => 'Contact & Directions',
            'description' => 'Contact Danks & Strydom Physiotherapy in Glen Marais, Kempton Park. Request an appointment and confirm directions before your visit.',
            'heading' => 'Contact and directions',
            'intro' => 'Request an appointment or ask the practice a question. An enquiry does not confirm an appointment.',
            'sections' => [
            ],
            'review_sections' => [
                'Arranging an appointment' => 'Please arrange an appointment before visiting. Call the practice during opening hours to check availability, including appointments for the same day. You can also request an appointment by email or through our website.',
                'When your booking is confirmed' => 'Walk-ins can be accommodated only when an appointment slot is available; please speak to reception on arrival. Website and email enquiries are appointment requests. Your appointment is confirmed once the practice agrees a date and time with you.',
            ],
        ],
        'services' => [
            'path' => '/services',
            'published' => true,
            'title' => 'Physiotherapy Services in Kempton Park',
            'description' => 'Back and neck pain physiotherapy, sports injury rehabilitation and post-operative rehabilitation in Glen Marais, Kempton Park.',
            'heading' => 'Physiotherapy services',
            'intro' => 'Explore our physiotherapy services, provided by Elize Strydom and Cheryl Myburgh.',
            'sections' => [
                'Preparing for your visit' => 'Patients are not expected to bring anything to their appointment.',
                'Request an appointment' => 'Contact the practice to discuss availability. Sending an enquiry does not confirm an appointment.',
            ],
        ],
        'back-neck-pain' => [
            'path' => '/services/back-neck-pain',
            'published' => false,
            'title' => 'Back & Neck Pain Physio in Kempton Park',
            'description' => 'Ask Danks & Strydom in Glen Marais about physiotherapy for back and neck pain and arranging an assessment.',
            'heading' => 'Back and neck pain',
            'intro' => 'Danks & Strydom offers physiotherapy for back and neck pain in Glen Marais, Kempton Park.',
            'sections' => [
                'Your first appointment' => 'Back or neck pain can make everyday activities uncomfortable. At your first appointment, you will complete a patient-information form and discuss your symptoms, how they affect your daily activities and what you would like help with. Your physiotherapist will assess your movement and the affected area, explain the findings and discuss appropriate treatment. Advice and any exercises will be tailored to your assessment.',
                'Your physiotherapists' => 'Elize Strydom and Cheryl Myburgh both provide this service. Contact the practice to discuss your needs and arrange an assessment.',
                'Appointment length and preparation' => 'Appointments are one hour. Patients are not expected to bring anything to their appointment.',
                'Follow-up appointments' => 'Your physiotherapist will discuss whether further appointments are needed and when you should return. Follow-up timing depends on your assessment and progress. If you need advice before your next appointment, contact the practice by telephone or message to discuss whether an earlier visit is needed.',
            ],
        ],
        'sports-injury-rehabilitation' => [
            'path' => '/services/sports-injury-rehabilitation',
            'published' => false,
            'title' => 'Sports Physio in Kempton Park',
            'description' => 'Ask Danks & Strydom in Glen Marais about sports injury rehabilitation and arranging a physiotherapy appointment.',
            'heading' => 'Sports injury rehabilitation',
            'intro' => 'Danks & Strydom offers sports injury rehabilitation in Glen Marais, Kempton Park.',
            'sections' => [
                'Your first appointment' => 'Whether an injury is affecting your sport, training or everyday movement, an assessment helps identify the next step. After completing a patient-information form, you will discuss the injury, your activity and your goals. Your physiotherapist will assess the affected area and relevant movements, then discuss treatment and rehabilitation suited to your needs. Guidance on returning to activity will depend on your assessment and progress.',
                'Your physiotherapists' => 'Elize Strydom and Cheryl Myburgh both provide this service. Contact the practice to discuss your needs and arrange an assessment.',
                'Appointment length and preparation' => 'Appointments are one hour. Patients are not expected to bring anything to their appointment.',
                'Follow-up appointments' => 'Your physiotherapist will discuss whether further appointments are needed and when you should return. Follow-up timing depends on your assessment and progress. If you need advice before your next appointment, contact the practice by telephone or message to discuss whether an earlier visit is needed.',
            ],
        ],
        'post-operative-rehabilitation' => [
            'path' => '/services/post-operative-rehabilitation',
            'published' => false,
            'title' => 'Post-Operative Physio in Kempton Park',
            'description' => 'Enquire about physiotherapy after surgery at Danks & Strydom in Glen Marais, Kempton Park.',
            'heading' => 'Rehabilitation after surgery',
            'intro' => 'Danks & Strydom offers post-operative rehabilitation in Glen Marais, Kempton Park. Contact the practice to discuss your procedure and appointment availability.',
            'sections' => [
                'Your first appointment' => 'Physiotherapy after surgery is tailored to your procedure and stage of recovery. At your first appointment, you will complete a patient-information form and discuss your operation, current difficulties and any instructions or restrictions given by your surgical team. Your physiotherapist will assess your movement and function and discuss appropriate treatment and rehabilitation.',
                'Your physiotherapists' => 'Elize Strydom and Cheryl Myburgh both provide this service. Contact the practice to discuss your needs and arrange an assessment.',
                'Appointment length and preparation' => 'Appointments are one hour. Patients are not expected to bring anything to their appointment.',
                'Follow-up appointments' => 'Your physiotherapist will discuss whether further appointments are needed and when you should return. Follow-up timing depends on your assessment and progress. If you need advice before your next appointment, contact the practice by telephone or message to discuss whether an earlier visit is needed.',
            ],
        ],
        'patient-information' => [
            'path' => '/patient-information',
            'published' => false,
            'title' => 'Patient Information',
            'description' => 'Prepare for your visit to Danks & Strydom Physiotherapy in Glen Marais, Kempton Park. Contact the practice for appointment and payment details.',
            'heading' => 'Before your first appointment',
            'intro' => 'Practical information to help you arrange your appointment and prepare for your visit.',
            'sections' => [
                'Arranging an appointment' => 'Please arrange an appointment before visiting. Call the practice during opening hours to check availability, including appointments for the same day. You can also request an appointment by email or through our website.',
                'When your booking is confirmed' => 'Walk-ins can be accommodated only when an appointment slot is available; please speak to reception on arrival. Website and email enquiries are appointment requests. Your appointment is confirmed once the practice agrees a date and time with you.',
                'Your first appointment' => 'Appointments are one hour. New patients complete a patient-information form. Your physiotherapist will assess you before providing appropriate treatment.',
                'What to bring' => 'Patients are not expected to bring anything to their appointment.',
                'Follow-up appointments' => 'Your physiotherapist will discuss whether further appointments are needed and when you should return. Follow-up timing depends on your assessment and progress. If you need advice before your next appointment, contact the practice by telephone or message to discuss whether an earlier visit is needed.',
                'Referrals' => 'You can book directly with the practice without a doctor’s referral. If you intend to use medical aid, check whether your scheme has any separate requirements.',
                'Fees and payment' => 'Contact the practice for current consultation fees. Cash and card payments are accepted. Please ask reception about medical-aid payment arrangements.',
                'Medical aid' => 'Please contact reception to confirm medical-aid claim arrangements and any amount payable by you. Check your benefits and requirements with your scheme before your appointment.',
                'Cancellations and rescheduling' => 'Please give at least 24 hours’ notice if you need to cancel or reschedule. With less than 24 hours’ notice, you may be liable for the full appointment fee. Contact the practice to change your booking.',
            ],
        ],
    ],
];
